const express = require("express");
const cors = require("cors");
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.get("/", (req, res) => res.json({ success: true, message: "HRMS Complete Workflow API working" }));
app.use("/api/auth", require("./src/routes/authRoutes"));
app.use("/api/company", require("./src/routes/companyRoutes"));
app.use("/api/roles", require("./src/routes/roleRoutes"));
app.use("/api/employees", require("./src/routes/employeeRoutes"));
app.use("/api/recruitment", require("./src/routes/recruitmentRoutes"));
app.use("/api/onboarding", require("./src/routes/onboardingRoutes"));
app.use("/api/attendance", require("./src/routes/attendanceRoutes"));
app.use("/api/leaves", require("./src/routes/leaveRoutes"));
app.use("/api/projects", require("./src/routes/projectRoutes"));
app.use("/api/tasks", require("./src/routes/taskRoutes"));
app.use("/api/payroll", require("./src/routes/payrollRoutes"));
app.use("/api/documents", require("./src/routes/documentRoutes"));
app.use("/api/assets", require("./src/routes/assetRoutes"));
app.use("/api/bpo", require("./src/routes/bpoRoutes"));
app.use("/api/reports", require("./src/routes/reportRoutes"));
app.use("/api/dashboard", require("./src/routes/dashboardRoutes"));
module.exports = app;
